use_cuda: true
data_parallel: true
num_epochs: 1000
output_dir: experiments/cifar10

model:
  name: efficientnet_b0
  num_classes: 10
  in_channels: 3

dataset:
  name: cifar10_dataloaders
  root: data
  batch_size: 256
  image_size: 64
  num_workers: 8

optimizer:
  name: SGD
  lr: 1.e-2
  weight_decay: 1.e-4
  nesterov: true

scheduler:
  name: CosineAnnealingLR
  T_max: 1000
  eta_min: 1.e-5
