use_cuda: true
data_parallel: true
num_epochs: 350
output_dir: experiments/cifar10

model:
  name: efficientnet_b0
  num_classes: 10
  in_channels: 3

dataset:
  name: cifar10_dataloaders
  root: data
  batch_size: 128
  image_size: 64
  num_workers: 0

optimizer:
  name: SGD
  lr: 1e-3
  weight_decay: 1e-4

scheduler:
  name: StepLR
  step_size: 10
