use_cuda: true
data_parallel: true
num_epochs: 90
output_dir: experiments/imagenet

model:
  name: efficientnet_b0
  num_classes: 1000

dataset:
  name: imagenet_dataloaders
  root: data
  batch_size: 32
  image_size: 224
  num_workers: 16

optimizer:
  name: TFRMSprop
  lr: 0.0125
  rho: 0.9
  momentum: 0.9
  eps: 1.e-3
  warmup: 200185
  weight_decay: 1.e-5

scheduler:
  name: ExponentialLR
  gamma: 0.98738885893
