use_cuda: true
data_parallel: true
num_epochs: 40
output_dir: experiments/mnist

model:
  name: efficientnet_b0
  num_classes: 10
  in_channels: 1

dataset:
  name: mnist_dataloaders
  root: data
  batch_size: 128
  image_size: 32
  num_workers: 0

optimizer:
  name: Adam
  lr: 0.001

scheduler:
  name: StepLR
  step_size: 20
