use_cuda: true
data_parallel: true
num_epochs: 20
output_dir: outputs

model:
  name: efficientnet_b0
  num_classes: 10

dataset:
  name: mnist_dataloaders
  root: data
  batch_size: 128
  image_size: 224

optimizer:
  name: SGD
  lr: 0.1

scheduler:
  name: StepLR
  step_size: 10
